In [1]:
import numpy as np

a=np.array([1,2,3])
print(a+5)


[6 7 8]


In [5]:
a=np.array([[10,20,30],[1,2,3]])
b=np.array([[1,2,3],[10,20,30]])

print(a @ b.T)

[[ 140 1400]
 [  14  140]]


In [7]:
a=np.array([1,2,3,4,5])
a=a.reshape(5,1)
print(a)


[[1]
 [2]
 [3]
 [4]
 [5]]
